name: 'Blossom Action'
description: 'Run blossom ci related task '
inputs:
  task:  # id of input
    description: 'task to perform'
    default: 'scan'
branding:
  icon: 'activity'  
  color: 'green'
runs:
  using: "composite"
  steps: 
    - run: chmod +x ${{ github.action_path }}/script.sh
      shell: bash
    - run: ${{ github.action_path }}/script.sh
      shell: bash
